### ISSUE TITLE
Line 45

### ISSUE THREAD

**Issue by AboTheeb** [NeloF4/brutegmail#1]
Traceback (most recent call last):
  File "Hellow.py", line 45, in <module>
    smtpserver.login(user, password)
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 611, in login
    AUTH_PLAIN + " " + encode_plain(user, password))
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 395, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 369, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by Joseph81271** [comment]
I am getting the same error. Did you fix it?
